<?php

namespace Admin\AdmBundle\Entity\Repositories;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\DoctrineExtention;

/**
 * GamesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamesInstallRepository extends EntityRepository{
  public function findOne($conn,$uniq_index){
    $statement = $conn->prepare('
      SELECT * FROM   `games_install` 
      WHERE id= :uniq_index
    ');
    $statement->bindValue('uniq_index',$uniq_index);
    $statement->execute();   
      
    $all = $statement->fetchAll();
  
    if(count($all)>0){
      return $all;
    }else{
      return array();
    }      
  
  }
  
  public function getAll($conn){
    $statement = $conn->prepare('
			SELECT a.id
           , a.attraction_id
           , a.dateadd
           , c.company
           , d.name game
        FROM games_install a
  INNER JOIN attractions b
          ON a.attraction_id=b.id
  INNER JOIN clients c
          ON a.client_id=c.id
  INNER JOIN games d
          ON a.game_id=d.id
    ORDER BY a.id DESC
    ');
    $statement->execute();   
      
    $all = $statement->fetchAll();
  
    if(count($all)>0){
      return $all;
    }else{
      return array();
    }      
  
  }
  

}

