parameters:
#    common_cifra.example.class: Common\CifraBundle\Example

services:
#    common_cifra.example:
#        class: %common_cifra.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
