blogger_blog_may:
    pattern:  /hello/{page}
    defaults: { _controller: BloggerBlogBundle:Default:index, page: 1}
    requirements:
        page:  \d+   
        
blogger_blog_may_main:
    pattern:  /{page}
    defaults: { _controller: BloggerBlogBundle:Default:index, page: 1}
    requirements:
        page:  \d+

