parameters:
#    admin_adm.example.class: Admin\AdmBundle\Example

services:
#    admin_adm.example:
#        class: %admin_adm.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
