<?php

namespace Hello\TestBundle\Entity\Repositories;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\DoctrineExtention;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamesRepository extends EntityRepository
{

  public function findOne($conn,$uniq_index){
    
  
    $statement = $conn->prepare( '
          SELECT * FROM   `news_has_news_tags` as has
          LEFT JOIN `news_tags` AS tag ON tag.news_tag_uniq_index = has.news_tags_id
          WHERE has.video_id = :uniq_index
        ORDER BY tag.tag_ves DESC
    ');
    $statement->bindValue('uniq_index',$uniq_index);
    $statement->execute();   
      
    $all = $statement->fetchAll();
  
    if(count($all) >0 ) {
      return $all ;
    }else{
      return array();
    }      
  
  
  
  }

}

